version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - cp ./settings.xml /opt/maven/conf/settings.xml
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain uautk --domain-owner 923928531961 --query authorizationToken --output text`
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 923928531961.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - mvn -version
      - mvn clean install deploy
cache:
  paths:
    - '/root/.m2/**/*'  

